### ISSUE TITLE
Case sensitive settigs (LeoCAD output)

### ISSUE THREAD

**Issue by Symbian9** [TobyLobster/ImportLDraw#7]
When try import .ldr/.mpd files, created and saved using LeoCAD, ImportLDraw can'd do it.

It's look like LeoCAD output issue

* https://github.com/leozide/leocad/issues/64

But, it would be cool if add setting checkbox to ImportLDraw's file chooser dialog:

* [x] Case sensitive import

If it will be unchecked then ImportLDraw should ignore case sizes of models & parts names inside imported files.

**Comment by Symbian9** [comment]
> Where did you see that names are case sensitive?

I detect this thing when tryed import in Blender (using "ImportLDraw" addon) .mpd/.ldr produced by LeoCAD.

ImportLDraw addon is case sensitive, so can't import such files:
* LeoCAD output (UPPERCASED names of parts & models, but `0 FILE` strings casesensitive)
```
0 FILE Sabah FreeStyle promotional set #1779.mpd
1 16 0 0 0 1 0 0 0 1 0 0 0 1 HELICOPTER #1779-1.LDR
1 16 0 0 0 1 0 0 0 1 0 0 0 1 SEAPLANE #1779-1.LDR
1 4 0 -8 -260 1 0 0 0 1 0 0 0 1 3022.DAT
1 16 0 0 0 1 0 0 0 1 0 0 0 1 SNOWMOBILE #1779-1.LDR
1 226 0 -24 -210 1 0 0 0 1 0 0 0 1 3004.DAT
0 NOFILE
0 FILE Seaplane #1779-1.ldr
1 4 0 160 10 1 0 0 0 1 0 0 0 1 3022.DAT
1 1 -29.997921 200 -10.005785 0.000026 0 1 0 1 0 -1 0 0.000026 3710.DAT
1 1 30.001064 200 -10.004789 0.000026 0 1 0 1 0 -1 0 0.000026 3710.DAT
1 4 0.000002 160 -40.003151 0.000026 0 1 0 1 0 -1 0 0.000026 3021.DAT
1 4 -0.000566 168 -9.996567 -1 0 -0.000053 0 1 0 0.000053 0 -1 3020.DAT
1 47 0.006355 136 -20.010002 -1 0 0.000053 0 1 0 -0.000053 0 -1 3039.DAT
1 226 0 136 -60 1 0 0 0 1 0 0 0 1 3004.DAT
1 226 0 176 -10 1 0 0 0 1 0 0 0 1 3022.DAT
1 226 0 168 -10 1 0 0 0 1 0 0 0 1 4871.DAT
1 1 0 192 -10 1 0 0 0 1 0 0 0 1 3020.DAT
0 NOFILE
0 FILE Helicopter #1779-1.ldr
1 4 0 -264 10 1 0 0 0 1 0 0 0 1 3022.DAT
1 1 -9.998962 -296 29.994736 0.000026 0 1 0 1 0 -1 0 0.000026 3710.DAT
1 1 10.002106 -296 -50.00531 0.000026 0 1 0 1 0 -1 0 0.000026 3710.DAT
1 4 -0.001038 -232 -0.003151 0.000026 0 1 0 1 0 -1 0 0.000026 3021.DAT
1 4 -0.00267 -264 -49.996567 0.000026 0 -1 0 1 0 1 0 0.000026 3020.DAT
1 47 0.005295 -288 -0.010002 -1 0 0.000053 0 1 0 -0.000053 0 -1 3039.DAT
1 226 0 -288 -20 1 0 0 0 1 0 0 0 1 3004.DAT
1 226 0 -256 -10 1 0 0 0 1 0 0 0 1 3022.DAT
1 226 0 -256 -10 1 0 0 0 1 0 0 0 1 4871.DAT
1 1 0 -248 -10 1 0 0 0 1 0 0 0 1 3020.DAT
0 NOFILE
0 FILE Snowmobile #1779-1.ldr
1 1 -29.997921 -8 -10.005785 0.000026 0 1 0 1 0 -1 0 0.000026 3710.DAT
1 1 30.001068 -8 -10.004791 0.000026 0 1 0 1 0 -1 0 0.000026 3710.DAT
1 4 0.000002 -64 -40.003151 0.000026 0 1 0 1 0 -1 0 0.000026 3021.DAT
1 4 -0.000568 -16 -9.996567 -1 0 -0.000053 0 1 0 0.000053 0 -1 3020.DAT
1 47 0.006355 -56 -20.010002 -1 0 0.000053 0 1 0 -0.000053 0 -1 3039.DAT
1 226 0 -24 -10 1 0 0 0 1 0 0 0 1 3022.DAT
1 226 0 -24 -10 1 0 0 0 1 0 0 0 1 4871.DAT
1 1 0 -32 -10 0.000026 0 -1 0 1 0 1 0 0.000026 3020.DAT
0 NOFILE
```
* ImportLDraw supported output (fully casensitive)
```
0 FILE Sabah FreeStyle promotional set #1779.ldr
1 16 0 0 0 1 0 0 0 1 0 0 0 1 Helicopter #1779-1.ldr
1 16 0 0 0 1 0 0 0 1 0 0 0 1 Seaplane #1779-1.ldr
1 4 0 -8 -260 1 0 0 0 1 0 0 0 1 3022.dat
1 16 0 0 0 1 0 0 0 1 0 0 0 1 Snowmobile #1779-1.ldr
1 226 0 -24 -210 1 0 0 0 1 0 0 0 1 3004.dat
0 NOFILE
0 FILE Seaplane #1779-1.ldr
1 4 0 160 10 1 0 0 0 1 0 0 0 1 3022.dat
1 1 -29.997921 200 -10.005785 0.000026 0 1 0 1 0 -1 0 0.000026 3710.dat
1 1 30.001064 200 -10.004789 0.000026 0 1 0 1 0 -1 0 0.000026 3710.dat
1 4 0.000002 160 -40.003151 0.000026 0 1 0 1 0 -1 0 0.000026 3021.dat
1 4 -0.000566 168 -9.996567 -1 0 -0.000053 0 1 0 0.000053 0 -1 3020.dat
1 47 0.006355 136 -20.010002 -1 0 0.000053 0 1 0 -0.000053 0 -1 3039.dat
1 226 0 136 -60 1 0 0 0 1 0 0 0 1 3004.dat
1 226 0 176 -10 1 0 0 0 1 0 0 0 1 3022.dat
1 226 0 168 -10 1 0 0 0 1 0 0 0 1 4871.dat
1 1 0 192 -10 1 0 0 0 1 0 0 0 1 3020.dat
0 NOFILE
0 FILE Helicopter #1779-1.ldr
1 4 0 -264 10 1 0 0 0 1 0 0 0 1 3022.dat
1 1 -9.998962 -296 29.994736 0.000026 0 1 0 1 0 -1 0 0.000026 3710.dat
1 1 10.002106 -296 -50.00531 0.000026 0 1 0 1 0 -1 0 0.000026 3710.dat
1 4 -0.001038 -232 -0.003151 0.000026 0 1 0 1 0 -1 0 0.000026 3021.dat
1 4 -0.00267 -264 -49.996567 0.000026 0 -1 0 1 0 1 0 0.000026 3020.dat
1 47 0.005295 -288 -0.010002 -1 0 0.000053 0 1 0 -0.000053 0 -1 3039.dat
1 226 0 -288 -20 1 0 0 0 1 0 0 0 1 3004.dat
1 226 0 -256 -10 1 0 0 0 1 0 0 0 1 3022.dat
1 226 0 -256 -10 1 0 0 0 1 0 0 0 1 4871.dat
1 1 0 -248 -10 1 0 0 0 1 0 0 0 1 3020.dat
0 NOFILE
0 FILE Snowmobile #1779-1.ldr
1 1 -29.997921 -8 -10.005785 0.000026 0 1 0 1 0 -1 0 0.000026 3710.dat
1 1 30.001068 -8 -10.004791 0.000026 0 1 0 1 0 -1 0 0.000026 3710.dat
1 4 0.000002 -64 -40.003151 0.000026 0 1 0 1 0 -1 0 0.000026 3021.dat
1 4 -0.000568 -16 -9.996567 -1 0 -0.000053 0 1 0 0.000053 0 -1 3020.dat
1 47 0.006355 -56 -20.010002 -1 0 0.000053 0 1 0 -0.000053 0 -1 3039.dat
1 226 0 -24 -10 1 0 0 0 1 0 0 0 1 3022.dat
1 226 0 -24 -10 1 0 0 0 1 0 0 0 1 4871.dat
1 1 0 -32 -10 0.000026 0 -1 0 1 0 1 0 0.000026 3020.dat
0 NOFILE
```

Inside LDraw library all names of .dat files inside `../ldraw/parts/` folder include only lowercase letters, but inside all `../ldraw/models/Note*.txt` files there is mix of lower- & uppercase parts names (`*.DAT` mixed with `.dat`)

According all above I created two issues:
* for LeoCAD - keep case sensitive names of parts & models inside saved files;
* for ImportLDraw - add option to ignore case sensitive naming of parts & models inside imported files.

**Comment by Symbian9** [comment]
From http://www.ldraw.org/article/512
> **File Name**
>
> Filenames must not be longer than 25 characters (including the extension) and must only contain the following characters: `a-z`, `A-Z`, `0-9`, `_`, and `-` (to avoid confusion with English grammar, comma is not a permitted character). While both upper and lower case letters are permitted in filenames, filenames are case-insensitive. Currently, all official parts are issued with upper-case only names.
>
> **Extension**
>
> All files in the LDraw Parts Library are required to carry the `.DAT` extension.

According this ` ` (space) not allowed in names of models (LeoCAD now allow "spaces" and non-latin letters, so this is issue and must be fixed)

For the parts naming `.DAT` look like correct (this is issue only for ImportLDraw).

**Comment by Symbian9** [comment]
https://github.com/leozide/leocad/issues/64#issuecomment-315456261

**Comment by BertVanRaemdonck** [comment]
#10 solves this issue, but not in the way you suggested. I thought adding yet another option would only clutter the menu, especially since it can be done completely automatically. The code in the pull request first tries to find a case sensitive match, and when it doesn't, tries to find a case insensitive match, so both cases are covered by the code. I've tested it with the model you uploaded, and even with some crazy variations on it, and it worked. I hope this is of use to you!

**Comment by TobyLobster** [comment]
I've just released a new version which includes a similar fix. (Looks like we were both working on this at the same time @BertVanRaemdonck)

**Comment by Symbian9** [comment]
Tnx, this is good news!

Look like in LeoCAD case issue was fixed too:

* https://github.com/leozide/leocad/commit/82528a2c7a0d44173e1d21e9fb21621d91333922

But, anyway this could be helpfull with many MPD-files produced before those fixes.

**Comment by mardy** [comment]
Hi! This bug is not fixed, I can still reproduce it. But if I apply the changes proposed in #10 , then it works. I can provide a file which shows the issue, if needed.

**Comment by TobyLobster** [comment]
If you could supply an example that shows the issue that would be useful to help me identify and fix the problem. Thanks.

**Comment by mardy** [comment]
I'm quite sure it was this file, but now that I just tried again it's working (and it's strange, because I didn't update ImportLDraw or Blender):
[6073 - Knight's Castle.mpd.gz](https://github.com/TobyLobster/ImportLDraw/files/1633044/6073.-.Knight.s.Castle.mpd.gz)

Well, have look and see if you spot something wrong with it, otherwise feel free to close this issue and sorry for the noise. :-)

**Comment by TobyLobster** [comment]
Thank you that example was useful. I've uploaded a new version 1.1.5 of the importer that fixes the issue.
